# Generated by Django 4.1.7 on 2026-02-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_leaderboard_calories_leaderboard_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
